"""
Contains the list of JOREK parameters for which values do not affect equilibrium (and
so STARWALL) solving in JOREK.

Currently, JOREK parameters on which equilibrim and STARWALL are considered invariant:
    - plasma resistivity and viscosity parameters
        - eta, eta_ohmic, eta_T_dependent, T_max_eta, T_max_eta_ohm,
            visco, visco_T_dependent, visco_par, eta_num, visco_num, visco_par_num
    - wall resistivity
        - wall_resistivity_fact, wall_resistivity
    - particle and heat diffusion terms
        - D_perp, D_par, D_perp_imp, D_par_imp, ZK_perp, ZK_par, ZK_par_max,
            ZK_i_perp, ZK_e_perp, ZK_i_par, ZK_e_par, D_neutral_x, D_neutral_y,
            D_neutral_p, ZKpar_T_dependent, D_perp_num, Zk_perp_num, Dn_perp_num,
            Zk_i_perp_num, Zk_e_perp_num, use_sc, D_perp_sc_num, D_par_sc_num,
            Dn_pol_sc_num, Dn_p_sc_num, ZK_perp_sc_num, ZK_par_sc_num, ZK_i_perp_sc_num,
            ZK_i_par_sc_num, ZK_e_perp_sc_num, ZK_e_par_sc_num, ZK_prof_neg, ZK_par_neg,
            ZK_prof_neg_thresh, ZK_par_neg_thresh, ZK_e_prof_neg, ZK_e_par_neg,
            ZK_e_prof_neg_thresh, ZK_e_par_neg_thresh, ZK_i_prof_neg, ZK_i_par_neg,
            ZK_i_prof_neg_thresh, ZK_i_par_neg_thresh, D_imp_extra_R, D_imp_extra_Z,
            D_imp_extra_p, D_imp_extra_neg, D_imp_extra_neg_thresh
"""

STARWALL_INVARIANTS = [
    "eta",
    "eta_ohmic",
    "eta_T_dependent",
    "T_max_eta",
    "T_max_eta_ohm",
    "visco",
    "visco_T_dependent",
    "visco_par",
    "eta_num",
    "visco_num",
    "visco_par_num",
    "wall_resistivity_fact",
    "wall_resistivity",
    "D_perp",
    "D_par",
    "D_perp_imp",
    "D_par_imp",
    "ZK_perp",
    "ZK_par",
    "ZK_par_max",
    "ZK_i_perp",
    "ZK_e_perp",
    "ZK_i_par",
    "ZK_e_par",
    "D_neutral_x",
    "D_neutral_y",
    "D_neutral_p",
    "ZKpar_T_dependent",
    "D_perp_num",
    "Zk_perp_num",
    "Dn_perp_num",
    "Zk_i_perp_num",
    "Zk_e_perp_num",
    "use_sc",
    "D_perp_sc_num",
    "D_par_sc_num",
    "Dn_pol_sc_num",
    "Dn_p_sc_num",
    "ZK_perp_sc_num",
    "ZK_par_sc_num",
    "ZK_i_perp_sc_num",
    "ZK_i_par_sc_num",
    "ZK_e_perp_sc_num",
    "ZK_e_par_sc_num",
    "ZK_prof_neg",
    "ZK_par_neg",
    "ZK_prof_neg_thresh",
    "ZK_par_neg_thresh",
    "ZK_e_prof_neg",
    "ZK_e_par_neg",
    "ZK_e_prof_neg_thresh",
    "ZK_e_par_neg_thresh",
    "ZK_i_prof_neg",
    "ZK_i_par_neg",
    "ZK_i_prof_neg_thresh",
    "ZK_i_par_neg_thresh",
    "D_imp_extra_R",
    "D_imp_extra_Z",
    "D_imp_extra_p",
    "D_imp_extra_neg",
    "D_imp_extra_neg_thresh",
]
